name: Quality Gate

on:
  pull_request:
    branches: [develop, main, production]
  push:
    branches: [develop, main, production]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.9"
          channel: "stable"

      - uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            build/
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

      - name: Define environment
        id: env
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
            echo "env=dev" >> $GITHUB_OUTPUT
            echo "api=${{ secrets.API_BASE_URL_DEV }}" >> $     GITHUB_OUTPUT
            echo "group=devs" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "env=hml" >> $GITHUB_OUTPUT
            echo "api=${{ secrets.API_BASE_URL_HML }}" >> $GITHUB_OUTPUT
            echo "group=testers" >> $GITHUB_OUTPUT
          else
            echo "env=prod" >> $GITHUB_OUTPUT
            echo "api=${{ secrets.API_BASE_URL_PROD }}" >> $GITHUB_OUTPUT
            echo "group=prod-users" >> $GITHUB_OUTPUT
          fi

      - name: Create env.json
        run: |
          cat <<EOF > env.json
          {
            "ENV": "${{ steps.env.outputs.env }}",
            "API_BASE_URL": "${{ steps.env.outputs.api }}",
            "ENABLE_LOGS": false
          }
          EOF

      - name: Restore google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > android/app/google-services.json

      - name: Restore firebase_options.dart
        run: |
          echo "${{ secrets.FIREBASE_OPTIONS_BASE64 }}" | base64 --decode > lib/firebase_options.dart

      - run: flutter pub get

      - run: flutter analyze

      - run: flutter test --coverage

      - run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Coverage Gate 75%
        run: |
          COVERAGE=$(lcov --summary coverage/lcov.info | grep lines | awk '{print $2}' | sed 's/%//')
          REQUIRED=75
          VALUE=${COVERAGE%.*}

          echo "Coverage: $VALUE%"

          if [ "$VALUE" -lt "$REQUIRED" ]; then
            echo "Coverage below ${REQUIRED}%"
            exit 1
          fi
